//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uteba.WinLess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Progress
    {
        public int idProgress { get; set; }
        public int idStud { get; set; }
        public int lessCheck { get; set; }
    
        public virtual Students Students { get; set; }
    }
}
