//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uteba.WinLess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        public int idStudents { get; set; }
        public string fName { get; set; }
        public string lName { get; set; }
        public System.DateTime dob { get; set; }
        public int group { get; set; }
        public int available { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public int lessCheck { get; set; }
    
        public virtual Group Group1 { get; set; }
    }
}
